dist: trusty
language: go
go:
  - 1.8.3

install: go get -v github.com/spf13/hugo

script:
  - hugo -D

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: hugo
  local_dir: public
  target_branch: master
  email: $GITHUB_MAIL

branches:
  only:
    - hugo
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always