dist: trusty
language: go
go:
  - 1.8.3
before_script:
  - go get gopkg.in/yaml.v2
  - go get -u -v github.com/gohugoio/hugo
  - git clone --branch $TARGET_BRANCH $FULL_REPO $BUILD_FOLDER
script:
  - hugo
  
deploy:
  providers: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: weihanchen/weihanchen.github.io
  target_branch: master
  email: $GITHUB_MAIL

branches:
  only:
    - hexo
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always

env:
  global:
    - BUILD_FOLDER: public
    - GITHUB_REPO: "@github.com/weihanchen/weihanchen.github.io.git"
    - TARGET_BRANCH: "master"
    - FULL_REPO: "https://${GITHUB_TOKEN}${GITHUB_REPO}"