language: node_js
node_js:
  - 6.0.0
before_script:
  - npm install
  - git clone --branch $TARGET_BRANCH $FULL_REPO $BUILD_FOLDER
script:
  - hexo cl
  - hexo g
after_success:
  - cp README.md $BUILD_FOLDER
  - cd $BUILD_FOLDER
  - git config --global user.email "${GITHUB_MAIL}"
  - git config --global user.name "${GITHUB_USER}"
  - git status
  - git add .
  - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
  - git commit -m "Site updated:${MESSAGE}"
  - git push $FULL_REPO $TARGET_BRANCH
branches:
  only:
    - hexo
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always

env:
  global:
    - BUILD_FOLDER: public
    - GITHUB_REPO: "@github.com/weihanchen/weihanchen.github.io.git"
    - TARGET_BRANCH: "master"
    - FULL_REPO: "https://${GITHUB_TOKEN}${GITHUB_REPO}"