language: node_js
node_js:
  - 6.0.0
before_script:
  - npm install
script:
  - npm run build
after_success: ./scripts/deploy.sh
branches:
  only:
    - hexo
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always