language: node_js
node_js:
  - 6.0.0
before_script:
  - npm install
script:
  - hexo cl
  - hexo g
after_success:
  - cd $BUILD_FOLDER
  - git init
  - git config --global user.email "${GITHUB_MAIL}"
  - git config --global user.name "${GITHUB_USER}"
  - git add .
  - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
  - git commit -m "Site updated:${MESSAGE}"
  - git push --force "https://${GITHUB_TOKEN}${GITHUB_REPO}" $TARGET_BRANCH:$TARGET_BRANCH
branches:
  only:
    - hexo
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always

env:
  global:
    - BUILD_FOLDER: "public"
    - GITHUB_REPO: "@github.com/weihanchen/weihanchen.github.io.git"
    - TARGET_BRANCH: "master"